#!/bin/bash

python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/citeseer_ego_labeled.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.8 --learning_rate 0.001 --max_len 750 --disable_label --num_samples 152 --hidden_size 64 > res_citeseer_ego_nolabel_hiddensize_64_templerature_0.8.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/citeseer_ego_labeled.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.8 --learning_rate 0.001 --max_len 750 --disable_label --num_samples 152 --hidden_size 128 > res_citeseer_ego_nolabel_hiddensize_128_templerature_0.8.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/citeseer_ego_labeled.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.85 --learning_rate 0.001 --max_len 750 --disable_label --num_samples 152 --hidden_size 64 > res_citeseer_ego_nolabel_hiddensize_64_templerature_0.85.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/citeseer_ego_labeled.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.85 --learning_rate 0.001 --max_len 750 --disable_label --num_samples 152 --hidden_size 128 > res_citeseer_ego_nolabel_hiddensize_128_templerature_0.85.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/citeseer_ego_labeled.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.9 --learning_rate 0.001 --max_len 750 --disable_label --num_samples 152 --hidden_size 64 > res_citeseer_ego_nolabel_hiddensize_64_templerature_0.9.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/citeseer_ego_labeled.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.9 --learning_rate 0.001 --max_len 750 --disable_label --num_samples 152 --hidden_size 128 > res_citeseer_ego_nolabel_hiddensize_128_templerature_0.9.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/citeseer_ego_labeled.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.95 --learning_rate 0.001 --max_len 750 --disable_label --num_samples 152 --hidden_size 64 > res_citeseer_ego_nolabel_hiddensize_64_templerature_0.95.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/citeseer_ego_labeled.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.95 --learning_rate 0.001 --max_len 750 --disable_label --num_samples 152 --hidden_size 128 > res_citeseer_ego_nolabel_hiddensize_128_templerature_0.95.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/citeseer_ego_labeled.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 1 --learning_rate 0.001 --max_len 750 --disable_label --num_samples 152 --hidden_size 64 > res_citeseer_ego_nolabel_hiddensize_64_templerature_1.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/citeseer_ego_labeled.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 1 --learning_rate 0.001 --max_len 750 --disable_label --num_samples 152 --hidden_size 128 > res_citeseer_ego_nolabel_hiddensize_128_templerature_1.txt

python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/community_label.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.8 --learning_rate 0.001 --max_len 2200 --disable_label --num_samples 100 --hidden_size 64 > res_citeseer_community_nolabel_hiddensize_64_temperature_0.8_new.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/community_label.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.8 --learning_rate 0.001 --max_len 2200 --disable_label --num_samples 100 --hidden_size 128 > res_citeseer_community_nolabel_hiddensize_128_temperature_0.8_new.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/community_label.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.85 --learning_rate 0.001 --max_len 2200 --disable_label --num_samples 100 --hidden_size 64 > res_citeseer_community_nolabel_hiddensize_64_temperature_0.85_new.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/community_label.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.85 --learning_rate 0.001 --max_len 2200 --disable_label --num_samples 100 --hidden_size 128 > res_citeseer_community_nolabel_hiddensize_128_temperature_0.85_new.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/community_label.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.9 --learning_rate 0.001 --max_len 2200 --disable_label --num_samples 100 --hidden_size 64 > res_citeseer_community_nolabel_hiddensize_64_temperature_0.9_new.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/community_label.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.9 --learning_rate 0.001 --max_len 2200 --disable_label --num_samples 100 --hidden_size 128 > res_citeseer_community_nolabel_hiddensize_128_temperature_0.9_new.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/community_label.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.95 --learning_rate 0.001 --max_len 2200 --disable_label --num_samples 100 --hidden_size 64 > res_citeseer_community_nolabel_hiddensize_64_temperature_0.95_new.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/community_label.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.95 --learning_rate 0.001 --max_len 2200 --disable_label --num_samples 100 --hidden_size 128 > res_citeseer_community_nolabel_hiddensize_128_temperature_0.95_new.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/community_label.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 1 --learning_rate 0.001 --max_len 2200 --disable_label --num_samples 100 --hidden_size 64 > res_citeseer_community_nolabel_hiddensize_64_temperature_1_new.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/community_label.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 1 --learning_rate 0.001 --max_len 2200 --disable_label --num_samples 100 --hidden_size 128 > res_citeseer_community_nolabel_hiddensize_128_temperature_1_new.txt

python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/enzymes.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.8 --learning_rate 0.001 --max_len 150 --disable_label --num_samples 120 --hidden_size 64 > res_enzymes_hiddensize_64_temperature_0.8.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/enzymes.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.85 --learning_rate 0.001 --max_len 150 --disable_label --num_samples 120 --hidden_size 64 > res_enzymes_hiddensize_64_temperature_0.85.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/enzymes.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.9 --learning_rate 0.001 --max_len 150 --disable_label --num_samples 120 --hidden_size 64 > res_enzymes_hiddensize_64_temperature_0.9.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/enzymes.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.95 --learning_rate 0.001 --max_len 150 --disable_label --num_samples 120 --hidden_size 64 > res_enzymes_hiddensize_64_temperature_0.95.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/enzymes.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 1 --learning_rate 0.001 --max_len 150 --disable_label --num_samples 120 --hidden_size 64 > res_enzymes_hiddensize_64_temperature_1.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/enzymes.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.8 --learning_rate 0.001 --max_len 150 --disable_label --num_samples 120 --hidden_size 128 > res_enzymes_hiddensize_128_temperature_0.8.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/enzymes.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.85 --learning_rate 0.001 --max_len 150 --disable_label --num_samples 120 --hidden_size 128 > res_enzymes_hiddensize_128_temperature_0.85.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/enzymes.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.9 --learning_rate 0.001 --max_len 150 --disable_label --num_samples 120 --hidden_size 128 > res_enzymes_hiddensize_128_temperature_0.9.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/enzymes.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.95 --learning_rate 0.001 --max_len 150 --disable_label --num_samples 120 --hidden_size 128 > res_enzymes_hiddensize_128_temperature_0.95.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/enzymes.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 1 --learning_rate 0.001 --max_len 150 --disable_label --num_samples 120 --hidden_size 128 > res_enzymes_hiddensize_128_temperature_1.txt

python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/protein.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.8 --learning_rate 0.001 --max_len 160 --disable_label --num_samples 223 --hidden_size 64 > res_proteins_hiddensize_64_temperature_0.8.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/protein.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.85 --learning_rate 0.001 --max_len 160 --disable_label --num_samples 223 --hidden_size 64 > res_proteins_hiddensize_64_temperature_0.85.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/protein.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.9 --learning_rate 0.001 --max_len 160 --disable_label --num_samples 223 --hidden_size 64 > res_proteins_hiddensize_64_temperature_0.9.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/protein.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.95 --learning_rate 0.001 --max_len 160 --disable_label --num_samples 223 --hidden_size 64 > res_proteins_hiddensize_64_temperature_0.95.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/protein.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 1.0 --learning_rate 0.001 --max_len 160 --disable_label --num_samples 223 --hidden_size 64 > res_proteins_hiddensize_64_temperature_1.0.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/protein.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.8 --learning_rate 0.001 --max_len 160 --disable_label --num_samples 223 --hidden_size 128 > res_proteins_hiddensize_128_temperature_0.8.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/protein.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.85 --learning_rate 0.001 --max_len 160 --disable_label --num_samples 223 --hidden_size 128 > res_proteins_hiddensize_128_temperature_0.85.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/protein.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.9 --learning_rate 0.001 --max_len 160 --disable_label --num_samples 223 --hidden_size 128 > res_proteins_hiddensize_128_temperature_0.9.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/protein.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 0.95 --learning_rate 0.001 --max_len 160 --disable_label --num_samples 223 --hidden_size 128 > res_proteins_hiddensize_128_temperature_0.95.txt
python3 train.py --input_file_dfs /home/tabei/Dat/graph_dataset/original/protein.dfs_codes --epochs 1001 --train_rate 0.8 --temperature 1.0 --learning_rate 0.001 --max_len 160 --disable_label --num_samples 223 --hidden_size 128 > res_proteins_hiddensize_128_temperature_1.0.txt
